import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/redux/provider'
import 'remixicon/fonts/remixicon.css'


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Job on board',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.png'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
